import sys

with open('app/src/main/java/com/example/ui/AppViewModel.kt', 'r') as f:
    content = f.read()

content = content.replace(
    "fun addBusinessSpace(brandName: String, description: String, phoneNumber: String, latitude: Double, longitude: Double, logoUri: Uri?, onComplete: (String) -> Unit) {\n        viewModelScope.launch {\n            val uploadedLogoUrl = logoUri?.let { repository.uploadImage(it) } ?: \"\"\n            val space = BusinessSpace(\n                ownerId = currentUserId,\n                brandName = brandName,\n                description = description,\n                phoneNumber = phoneNumber,\n                latitude = latitude,\n                longitude = longitude,\n                logoUri = uploadedLogoUrl\n            )\n            repository.addBusinessSpace(space, onComplete)\n        }\n    }",
    "fun addBusinessSpace(brandName: String, description: String, phoneNumber: String, latitude: Double, longitude: Double, logoUri: Uri?, bannerUri: Uri?, onComplete: (String) -> Unit) {\n        viewModelScope.launch {\n            val uploadedLogoUrl = logoUri?.let { repository.uploadImage(it) } ?: \"\"\n            val uploadedBannerUrl = bannerUri?.let { repository.uploadImage(it) } ?: \"\"\n            val space = BusinessSpace(\n                ownerId = currentUserId,\n                brandName = brandName,\n                description = description,\n                phoneNumber = phoneNumber,\n                latitude = latitude,\n                longitude = longitude,\n                logoUri = uploadedLogoUrl,\n                bannerUri = uploadedBannerUrl\n            )\n            repository.addBusinessSpace(space, onComplete)\n        }\n    }\n\n    fun updateBusinessSpace(space: BusinessSpace, newLogoUri: Uri?, newBannerUri: Uri?, onComplete: () -> Unit) {\n        viewModelScope.launch {\n            val logoUrl = newLogoUri?.let { repository.uploadImage(it) } ?: space.logoUri\n            val bannerUrl = newBannerUri?.let { repository.uploadImage(it) } ?: space.bannerUri\n            val updatedSpace = space.copy(logoUri = logoUrl, bannerUri = bannerUrl)\n            repository.updateBusinessSpace(updatedSpace, onComplete)\n        }\n    }\n\n    fun updateSpaceProduct(product: SpaceProduct, newImageUris: List<Uri>, onComplete: () -> Unit) {\n        viewModelScope.launch {\n            val additionalImageUrls = newImageUris.mapNotNull { repository.uploadImage(it) }\n            val updatedProduct = product.copy(imageUrls = product.imageUrls + additionalImageUrls)\n            repository.updateSpaceProduct(updatedProduct)\n            onComplete()\n        }\n    }\n\n    fun updateSpaceProduct(product: SpaceProduct, onComplete: () -> Unit) {\n        repository.updateSpaceProduct(product)\n        onComplete()\n    }\n\n    fun deleteSpaceProduct(productId: String) {\n        repository.deleteSpaceProduct(productId)\n    }"
)

with open('app/src/main/java/com/example/ui/AppViewModel.kt', 'w') as f:
    f.write(content)

