name: Android Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode Keystore
        run: echo "MIIKZgIBAzCCChAGCSqGSIb3DQEHAaCCCgEEggn9MIIJ+TCCBcAGCSqGSIb3DQEHAaCCBbEEggWtMIIFqTCCBaUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFMq4vL0rEYlr7rvtgnrBE/3qLWKJAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ+zk+ce2bDvZaN6Rs5U0eJQSCBNCy+czaZkyZRPXtnQbWoAJgP8hiEgpKWapynfKeyUl4X1CFd9eBTI7a92OdykZ6RClC20UUrR00Z6k+dQjaqZu7sDQ9tODRSa6/31WBW9sfg7MJh5reXElvax5/74dpFgKqKiqgW+H0tvp+DUy6Pj0D/fJ2nNUlLmqx89MAHlGfCGbSXXTdnVWrxryKoiUPiV2W66NcAFloEpOpiW6BYndGpf31ZlK9vIg4MpiJc/sQPN1Djzy2wFCsYtp7FHv+NfWQDy3LtK3pFArtVHQoThc0jIXNpymJfYUEWX+C+8HG/1qK1HuaMPOt+AkeFwImPTrbi2hJXxeHmiB3tkciwwSTpo4MIiD/m/WF4PJR3RAbBOn9BKHnxM7Szw7QoGExtFfwy+RZRK07qRLWgIoFXg3t7XCJqCV95BgWq4iaEbj1b+6Jsq6Dy9jHbevmjwZH8ZK/tATMYjy/vmUOXwJLWV+AIfPgr5ew1L48XjQlPxOE/Xr2DZ9I8xJPp6WrFUh6Kq2Y6zZJ7UyhkQ+nGbV6J3f5Nxwz9artuat0jxrSP+av2je0ZADpKUepoYb1qQjbngsgEW8uX+63j5YUNkDcQF8PurhjC7r9Sxn2+ZDSd/3BJVne3BfqS00Q+tz7RnNDiyDf/tsn1iTqv036inRvfVjARk+5oU9hkmXIS84xoqVhEhAzy2q9lxKsLCWH0h5y5+KiBc7DiFo3Ad3TfgAi94UAc6yKhaiqThibJNOa2KC/I0LHVIbtPnbNF6xpUiG0ixdGdZGVdOJUhRHUpt4fgM6BWwvWaHWXd2Ywov8TQprm+3o/cZxPvf868YFhau5QjXJ9URwkN/B4ZLQmN1Q434lRfmKRrjDOMnIMYAPiVdbrViLU/Z+loApf4svwgYwCM/qoGQzuVgvL3JB+EkTv8YOZtBR4fVwjdc9DIJ3NBoX9p8yFjr05CS880rE+b2uQmyoxXyNsTtDOlh39MUytTkN40/0p23cumbagI+zBDlg8mTAoqHaEr1Vu1/vsEUzooVpqfbbTU3Si9LKNYSzoGjBNJ3oF0dPWuA6lxay/e52Bbg9Y7xL/diROWJOQ1uW5qZgxshPncwxEr9dRHJsobSvipaV7JVWSoCtCJUo/gEFp7B6n94bSLdaUf3gr5xdOJ9S+Y9CxvDOIOinEXG1XnpZhelIJzgmJ+ltHZKa9dEtrqLmAnY9WnSaHCoCBbqZYCU8hUbHhiKcIFkma6+Oj0+yfu/y2ohNlduEQLvLu3nD/OylM3uNiAzMv5fXc526kCxpof5flNcEjHZhuI/TWSGfJdqOqUD+YdvkwSHSxpRp/6QV1lWDL1XD2xvSrAL25GbubNfASJZ1p6qT4h+/YzQgpmKJuTVqyZmvYE1yaWidD0WKkHVeLM1PTvmaGhMbwVERNp0CsXxrAqw7r4at05iuRyDl6RJqK9YPtou2pktg+64DD1k2f4GsFj/hWpkf7a8HE4Ve4hRIGsmvncv03BeQkI4Y/Nuzc+gB1V+mzJgupptTOpqAOqb47hC/z85eqIWDNku5D7qJBg5stUAnpCHu/xj4dR41nelbe6ePR5+G2e71LK2+Pm7uNu+7xS4dkPXAfBt9cwG1Jj89MZKva2zyefR80vegjorKlrq80egXoeTFSMC0GCSqGSIb3DQEJFDEgHh4AYQBuAGQAcgBvAGkAZABkAGUAYgB1AGcAawBlAHkwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTc4MzEwNTQ4MTkzNDCCBDEGCSqGSIb3DQEHBqCCBCIwggQeAgEAMIIEFwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBTOfnA3EV0XTzso9ezKlrO78GCyKgICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEIDSEPjQjMWL6ZWDLvCDH6CAggOgv3l3GwIlm/GM8+OgAN71wH/JzVwC99a86o8VBSo0sVmAuMTpq15IOfxEt6GLmG0VVkLohA72KbuXcw83rSPqj4MgbEEgLVgF8biiYBIzuSl1qTeOl2tnU6skitOKomY++rse7aVRCi+jKKnBxzST0/84tz+ObqSNmvpYoSixwpVeT65ABCERA1qF7eGGGGNIEw72jdlhqPbUq64yI0KeOVKu3naFZ3TS8TycLWqAce8Hn0e9KHGUVlgYUE5ncWvaLQiCtIR0HfB1Bqn0LjDM49hhcJ+X0/5B7hwWCxJA7y1TbszsiK7jGUtXS4Jq5+IBHmDGuGLII+oX5QBXnHaM/GGJAGUFN1PKqyhPFCu4OAYwPf6614p3AUGmYbzGrp2hhwjkfefCJjcD2L7LgTatnpEymtO2oOV1CfZhXo+Y+jbXLgE7HVrSunM65rV9LMNfkOpSzlkoeAnnm1MKl5c08JbymRFpIrstttbhnOp5kO19ZFSgQlex+IBZqwvSFzRU5D7xbKCIeiSyRDmB7bUIOxuNspDimOTQlITgpCFCcT9XhcynlW2jdi5rrUEPgsPfAVOyRslrEKwzaHG08SS6q/6KfKzMhejrHr3yukCXi/tXAX4/EemUGnZ5r5an7d7KVlTLTHPP5PXEodCvH2CMP7V6yTB4e5v2BeeaX5FRT4cLNQMs/toOYsidRV05JslknNOB9MYy361SPZL++lVtv38dNCVlRnqIsYBq3IP4mlG3x8MMvrgosnuka4Dd0ciVUiIyB77eVEsZQUr3jTucPhUZ8f9DH1Ksh3NqJ7EqTYWv9nzF+Ri7avwBryI9Fs7QSIGDhE3sI35IqNjDo1MFPLeXiffOiYMtOQcDKlyfRwSzGhKZrxi63fFd3hIELowx2sMQ4j+vhSYzSmb1AQKXPLjchWa8S0C5KQmg/N6tao4LeMVpIPqnc/NZzvtrV9A+MIsmFLGtbJjzPSx9VfkNMwg9a5WfFjeYfpPpK29r13Y7PSqFJHAchMI7iVHBOOhCLUzUKN1x4YHbu2ncyHj4N24bBbxiEEuUqlUXrWxkxMKhatjaFcLcyPIfgj396ESREr4HOZCqXFD961/S5qYs8r5hbjnl8DRGt2AD1mXmOfEpQuw1LUWs70jNU0ubhqxWzIVEFJu0goMYa8Z1Y1Bazg4y6CzAH7BB0v/+EYJOvGCE2mwkdyMPoKfIIS3CidRoa53iVga4jw+9t5f3mL7tADBNMDEwDQYJYIZIAWUDBAIBBQAEIB13mzP5B9vmJcHOIqGHdZubTplyzSbigk/JMDlbpy1JBBSyO4nfH8kzUSwNe5tysBjGZeceewICJxA=" | base64 -d > debug.keystore

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
